version: "2"

services:

  apache:
    build:
      context: .
      dockerfile: Dockerfile-apache
    ports:
      - "80:80"
      - "443:443"
    links:
      - ember-app

  ember-app:
    build:
      context: .
      dockerfile: Dockerfile-ember
    expose:
      - 3000
